#!/usr/bin/env bash
export GIT_WORK_TREE=/home/pi/bekkboard

echo "-> checking out.."
git checkout -f

. $HOME/.nvm/nvm.sh
$NODE_VERSION="$(nvm current)"
echo "-> node version $NODE_VERSION"

echo "-> GUI: npm install.."
cd /home/pi/bekkboard/GUI/ && npm install

echo "-> server: npm install.."
cd /home/pi/bekkboard/server/ && npm install

echo "-> hardware: npm install.."
cd /home/pi/bekkboard/hardware/ && npm install
