#!/usr/bin/env bash
export GIT_WORK_TREE=/home/pi/bekkboard

echo "-> checking out.."
git checkout -f
git clean -fxd

echo "-> GUI: npm install.."
cd $GIT_WORK_TREE/GUI && npm install

echo "-> server: npm install.."
cd $GIT_WORK_TREE/server && npm install

echo "-> hardware: npm install.."
cd $GIT_WORK_TREE/hardware && npm install
