#!/usr/bin/env bash
export GIT_WORK_TREE=/home/pi/bekkboard

echo "-> checking out.."
git checkout -f

. $HOME/.nvm/nvm.sh
NODE_VERSION="$(nvm current)"
echo "-> node version $NODE_VERSION"

echo "-> GUI: npm install.."
cd $GIT_WORK_TREE/GUI && npm run compile-prod

echo "-> server: npm install.."
cd $GIT_WORK_TREE/server && npm install

echo "-> hardware: npm install.."
cd $GIT_WORK_TREE/hardware && npm install
